package dev.ultreon.ubo;

public class DataTypes {
    public static int BYTE = 0x01;
    public static int SHORT = 0x02;
    public static int INT = 0x03;
    public static int LONG = 0x04;
    public static int BIG_INT = 0x05;
    public static int FLOAT = 0x06;
    public static int DOUBLE = 0x07;
    public static int BIG_DEC = 0x08;
    public static int CHAR = 0x09;
    public static int BOOLEAN = 0x0a;
    public static int STRING = 0x20;
    public static int LIST = 0x30;
    public static int MAP = 0x31;
    public static int BYTE_ARRAY = 0x51;
    public static int INT_ARRAY = 0x52;
    public static int SHORT_ARRAY = 0x53;
    public static int LONG_ARRAY = 0x54;
    public static int FLOAT_ARRAY = 0x56;
    public static int DOUBLE_ARRAY = 0x57;
    public static int CHAR_ARRAY = 0x58;
    public static int BOOLEAN_ARRAY = 0x59;
    public static int UUID = 0x70;
    public static int BIT_SET = 0x80;
    public static int VECTOR_2 = 0x90;
    public static int VECTOR_3 = 0x91;
    public static int VECTOR_4 = 0x92;
    public static int INT_VECTOR_2 = 0x93;
    public static int INT_VECTOR_3 = 0x94;
    public static int INT_VECTOR_4 = 0x95;
    public static int LONG_VECTOR_2 = 0x96;
    public static int LONG_VECTOR_3 = 0x97;
    public static int LONG_VECTOR_4 = 0x98;
    public static int FLOAT_VECTOR_2 = 0x99;
    public static int FLOAT_VECTOR_3 = 0x9a;
    public static int FLOAT_VECTOR_4 = 0x9b;
    public static int DOUBLE_VECTOR_2 = 0x9c;
    public static int DOUBLE_VECTOR_3 = 0x9d;
    public static int DOUBLE_VECTOR_4 = 0x9e;
}
